
class AccountingPage(object):
    Accounting_header = "Credit"
    ShortInterestSummary_header = "Short Interest Summary"
    ShortInterestAccount_header = "Short Interest By Account"
    ShortInterestDepartment_header = "Short Interest Summary By Department"
    LFAAccounting_header = "LFA Accounting"
    AgencyLending_header = "Agency Lending Files"
    UnallocatedBorrow_header = "Unallocated Borrow Cost Allocation"
    InventoryAccount_header = "Inventory Account Profit Loss"
    Section31Fee_header = "Section31 Fee Accounting"
    BetaSection31Fee_header = "BETA Section31 Fee Reconciliation"
    Phase3Section31_header = "Phase3 Section31 Fee Reconciliation"
    Phase3OCC_header = "Phase3 OCC PassThrough Fees"
    Phase3NSCC_header = "Phase3 NSCC Pass Through Fees"
    BetaNSCC_header = "BETA NSCC PassThrough Fees"
    DebitInterest_header = "Debit Interest By Office"
    TNCMargin_header = "TNC Margin Concentration Accounts"
    GeneralLedger_header = "General Ledger"
    GeneralLedgerDetail_header = "General Ledger Detail"
    Phase3DTC_header = "Phase3 DTC Allocation"
    APDashboard_header = "AP Dashboard"
    IVANAccount_header = "IVAN Account OTC Trades"
    PABProjected_header = "PAB Projected Settlement"

    ShortDate = "ctl00_CC_ShortDateTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    SearchButton = "ctl00_CC_SearchBtn"
    AccountNumber = "ctl00_CC_AccountNumberTxt"
    TestAccount = "57048721"
    Date = "ctl00_CC_FileDateTxt"
    FromDate = "ctl00_CC_txtFromDate"
    ActualDate = "ctl00_CC_ActualDateTxt"

    AccountNumber_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_AccountNumber_LinkButton"
    AccountNumber_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_AccountNumberLabel"
    CSI_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_CSI_LinkButton"
    MSI_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_MSI_LinkButton"
    AccountName_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_AccountName_LinkButton"
    Sub_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_Sub_LinkButton"
    Sub_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_SubLabel"
    Department_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_Department_LinkButton"
    Department_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_DepartmentLabel"
    RepCode_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_RepCode_LinkButton"
    ContractAmount_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_ContractAmount_LinkButton"
    ContractAmount_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_ContractAmountLabel"
    DailyCharge_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_DailyCharge_LinkButton"
    DailyCharge_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_DailyChargeLabel"
    MTDCharge_header = "ctl00_CC_ShortInterestSummaryGridView_ctl01_MTDCharge_LinkButton"
    MTDCharge_element = "ctl00_CC_ShortInterestSummaryGridView_ctl02_MTDChargeLabel"

    ShortDate_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_ShortDate_LinkButton"
    ShortDate_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_ShortDateLabel"
    AccountNumber_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_AccountNumber_LinkButton"
    AccountNumber_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_AccountNumberLabel"
    Cusip_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_CUSIPLabel"
    Symbol_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_Symbol_LinkButton"
    Symbol_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_SymbolLabel"
    ShortQty_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_ShortQty_LinkButton"
    ShortQty_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_ShortQtyLabel"
    ContractAmount_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_ContractAmount_LinkButton"
    ContractAmount_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_ContractAmountLabel"
    Days_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_Days_LinkButton"
    Days_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_DaysLabel"
    DailyRate_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_DailyRate_LinkButton"
    DailyRate_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_DailyRateLabel"
    DailyCharge_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_DailyCharge_LinkButton"
    DailyCharge_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_DailyChargeLabel"
    MTDRate_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_MTDRate_LinkButton"
    MTDRate_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_MTDRateLabel"
    MTDCharge_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_MTDCharge_LinkButton"
    MTDCharge_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_MTDChargeLabel"
    DaysInCharge_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_DaysInCharge_LinkButton"
    DaysInCharge_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_DaysInChargeLabel"
    AvgCharge_header_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl01_AvgCharge_LinkButton"
    AvgCharge_element_1 = "ctl00_CC_ShortInterestByAccountGridView_ctl02_AvgChargeLabel"

    FileDate_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th"
    FileDate_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td"
    Department_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[2]"
    Department_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[2]"
    ShortInterest_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[3]"
    ShortInterest_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[3]"
    ExternalBorrowSpread_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[4]"
    ExternalBorrowSpread_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[4]"
    ExternalBorrowCost_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[5]"
    ExternalBorrowCost_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[5]"
    ExternalSpread_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[6]"
    ExternalSpread_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[6]"
    InternalBorrowSpread_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[7]"
    InternalBorrowSpread_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[7]"
    InternalBorrowCost_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[8]"
    InternalBorrowCost_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[8]"
    InternalSpread_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[9]"
    InternalSpread_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[9]"
    CNSFail_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[10]"
    CNSFail_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[10]"
    MarginExcess_header_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr/th[11]"
    MarginExcess_element_2 = "//table[@id='ctl00_CC_ShortInterestSummaryGridView']/tbody/tr[2]/td[11]"

    ShortInterest_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td"
    ShortInterest_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td"
    ExternalBorrow_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[2]"
    ExternalBorrow_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[2]"
    InternalBorrow_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[3]"
    InternalBorrow_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[3]"
    FailToDeliver_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[4]"
    FailToDeliver_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[4]"
    MarginExcess_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[5]"
    MarginExcess_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[5]"
    InternalBorrowSpread_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[6]"
    InternalBorrowSpread_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[6]"
    ExternalBorrowSpread_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[7]"
    ExternalBorrowSpread_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[7]"
    RemainingBalance_header_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr/td[8]"
    RemainingBalance_element_3 = "//div[@id='ctl00_CC_DataPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[8]"
    Description_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th"
    Department_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[2]"
    Department_element_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr[2]/td[2]"
    Account_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[3]"
    Account_element_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr[2]/td[3]"
    Debit_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[4]"
    Debit_element_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr[2]/td[4]"
    Credit_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[5]"
    Credit_element_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr[2]/td[5]"
    Net_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[6]"
    Net_element_3 = "ctl00_CC_LFAGridView_ctl02_NetLabel"
    Wash_header_3 = "//table[@id='ctl00_CC_LFAGridView']/tbody/tr/th[7]"
    Wash_element_3 = "ctl00_CC_LFAGridView_ctl02_NetOffsetLabel"

    SelectDepartment = "ctl00_CC_ddlDepartments"
    TestDepartment = "MiddleOffice"
    SelectDate = "ctl00_CC_ddlSettleDate"
    TestDate = "2021-11-10"
    ViewList_button = "ctl00_CC_btnViewList"
    Name_header_4 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th"
    UserName_header_4 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[2]"
    UpdateDate_header_4 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[3]"

    FileDate_header_5 = "File Date"
    FileDate_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td"
    Department_header_5 = "Department"
    Department_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[2]"
    DepartmentName_header_5 = "Department Name"
    DepartmentName_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[3]"
    TotalAllocated_header_5 = "Total Allocated Contract Value"
    TotalAllocated_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[4]"
    Days_header_5 = "Days"
    Days_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[5]"
    AverageDaily_header_5 = "Average Daily Contract Value"
    AverageDaily_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[6]"
    ContractValue_header_5 = "Contract Value %"
    ContractValue_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[7]"
    OriginalTotal_header_5 = "Original Total Allocated Cost"
    OriginalTotal_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[8]"
    AllocatedCost_header_5 = "Allocated Cost %"
    AllocatedCost_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[9]"
    StockLoan_header_5 = "Stock Loan Spread"
    StockLoan_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[10]"
    ExtraAllocated_header_5 = "Extra Allocated Cost"
    ExtraAllocated_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[11]"
    MarkupCredit_header_5 = "Markup Credit"
    MarkupCredit_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[12]"
    FinalTotal_header_5 = "Final Total Allocated Cost"
    FinalTotal_element_5 = "//table[@id='ctl00_CC_UnallocatedAllocationGrid']/tbody/tr[2]/td[13]"

    TradeDate_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_TradeDate_LinkButton"
    TradeDate_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_TradeDateLabel"
    Account_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_Account_LinkButton"
    Account_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_HyperLink1"
    Sub_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_Sub_LinkButton"
    Sub_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_SubLabel"
    AccountName_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_AccountName_LinkButton"
    AccountName_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_AccountNameLabel"
    Dept_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_Dept_LinkButton"
    Dept_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_DeptLabel"
    LongValue_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_LongValue_LinkButton"
    LongValue_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_LongValueLabel"
    ShortValue_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_ShortValue_LinkButton"
    ShortValue_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_ShortValueLabel"
    GrossValue_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_GrossValue_LinkButton"
    GrossValue_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_GrossValueLabel"
    RBH_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_RBH_LinkButton"
    RBH_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_RBHLabel"
    BeginProfit_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_BeginProfitLoss_LinkButton"
    BeginProfit_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_BeginProfitLossLabel"
    DailyProfits_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_DailyProfitLoss_LinkButton"
    DailyProfits_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_DailyProfitLossLabel"
    MTDProfit_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_MTDProfitLoss_LinkButton"
    MTDProfit_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_MTDProfitLossLabel"
    ShortInterest_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_ShortInterest_LinkButton"
    ShortInterest_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_ShortInterestLabel"
    LongRebate_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_LongRebate_LinkButton"
    LongRebate_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_LongRebateLabel"
    Treasury_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_Treasury_LinkButton"
    Treasury_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_TreasuryLabel"
    PaidDiv_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_PaidDiv_LinkButton"
    PaidDiv_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_PaidDivLabel"
    Total_header_6 = "ctl00_CC_ProfitLossGridView_ctl01_Total_LinkButton"
    Total_element_6 = "ctl00_CC_ProfitLossGridView_ctl02_TotalLabel"
    MarketValue_Title_6 = "//table[@id='ctl00_CC_ProfitLossGridView']/tbody/tr/th[2]"
    TradingProfit_Title_6 = "//table[@id='ctl00_CC_ProfitLossGridView']/tbody/tr/th[3]"
    Financing_Title_6 = "//table[@id='ctl00_CC_ProfitLossGridView']/tbody/tr/th[4]"
    Income_Title_6 = "//table[@id='ctl00_CC_ProfitLossGridView']/tbody/tr/th[5]"
    Total_Title_6 = "//table[@id='ctl00_CC_ProfitLossGridView']/tbody/tr/th[6]"

    MoveSection31Paid_Title_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr/th[2]"
    MoveSection31Collected_Title_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr/th[3]"
    Month_header_7 = "Month"
    Month_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[2]"
    ContraPartyMPID_header_7 = "ContraParty MPID"
    ContraPartyMPID_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[3]"
    ContraPartyDTC_header_7 = "ContraParty DTC"
    ContraPartyDTC_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[4]"
    ExecutionCnt_header_7 = "Execution Cnt"
    ExecutionCnt_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[5]"
    PrincipalAmount_header_7 = "Principal Amount"
    PrincipalAmount_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[6]"
    Section31FeeDebit_header_7 = "Section31 Fee Paid Debit 51080604"
    Section31FeeDebit_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[7]"
    Section31FeeCredit_header_7 = "Section31 Fee Paid Credit 78720173"
    Section31FeeCredit_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[8]"
    Section31FeeCollectedDebit_header_7 = "Section31 Fee Collected Debit 78720173"
    Section31FeeCollectedDebit_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[9]"
    Section31FeeCollectedCredit_header_7 = "Section31 Fee Collected Credit 48450604"
    Section31FeeCollectedCredit_element_7 = "//table[@id='ctl00_CC_Section31FeeAccountingGridView']/tbody/tr[3]/td[10]"

    SelectDate_8 = "ctl00_CC_FilterDropDown"
    TestDate_8 = "Dec 2020"
    Sub_header_8 = "Sub"
    Sub_element_8 = "//table[@id='ctl00_CC_Section31FeeReconciliationGridView']/tbody/tr[2]/td[1]"
    FirmName_header_8 = "FirmName"
    FirmName_element_8 = "//table[@id='ctl00_CC_Section31FeeReconciliationGridView']/tbody/tr[2]/td[2]"
    Month_header_8 = "Month"
    Month_element_8 = "//table[@id='ctl00_CC_Section31FeeReconciliationGridView']/tbody/tr[2]/td[3]"
    SecFeeAmt_header_8 = "SecFeeAmt"
    SecFeeAmt_element_8 = "//table[@id='ctl00_CC_Section31FeeReconciliationGridView']/tbody/tr[2]/td[4]"

    SelectDate_9 = "ctl00_CC_MonthDropDown"
    TestDate_9 = "Dec 2020"
    EntityCode_header_9 = "EntityCode"
    EntityCode_element_9 = "//table[@id='ctl00_CC_P3Sec31FeeReconciliationGridView']/tbody/tr[2]/td[1]"
    Month_header_9 = "Month"
    Month_element_9 = "//table[@id='ctl00_CC_P3Sec31FeeReconciliationGridView']/tbody/tr[2]/td[2]"
    SecFeeAmt_header_9 = "SecFeeAmt"
    SecFeeAmt_element_9 = "//table[@id='ctl00_CC_P3Sec31FeeReconciliationGridView']/tbody/tr[2]/td[3]"

    Month_header_10 = "Month"
    Month_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td"
    EntityCode_header_10 = "Entity Code"
    EntityCode_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[2]"
    EntityName_header_10 = "Entity Name"
    EntityName_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[3]"
    TotalTrades_header_10 = "Total Trades"
    TotalTrades_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[4]"
    TotalAmt_header_10 = "Total Contract Amt"
    TotalAmt_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[5]"
    TotalQty_header_10 = "Total Contract Qty"
    TotalQty_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[6]"
    CustomerContract_header_10 = "Customer Contract Qty"
    CustomerContract_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[7]"
    OCCClearing_header_10 = "OCC Clearing Fee"
    OCCClearing_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[8]"
    ORF_header_10 = "ORF"
    ORF_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[9]"
    Total_header_10 = "Total"
    Total_element_10 = "//table[@id='ctl00_CC_OccFeeGridView']/tbody/tr[2]/td[10]"

    Month_header_11 = "Month"
    Month_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td"
    FirmName_header_11 = "Firm Name"
    FirmName_header_12 = "FirmName"
    FirmName_element_11 = "Avatar Securities LLC"
    Shares_header_11 = "Shares"
    Shares_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[3]"
    Trades_header_11 = "Trades"
    Trades_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[4]"
    ValueInto_header_11 = "Value Into Net"
    ValueInto_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[5]"
    ValueOut_header_11 = "Value Out of Net"
    ValueOut_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[6]"
    Fee2481_header_11 = "2481 Fee"
    Fee2481_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[7]"
    Fee2481_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[8]"
    Fee2482_header_11 = "2482 Fee"
    Fee2482_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[8]"
    Fee2482_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[9]"
    Fee2483_header_11 = "2483 Fee"
    Fee2483_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[9]"
    Fee2483_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[10]"
    Fee2200_header_11 = "2200 Fee"
    Fee2200_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[10]"
    Fee2200_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[11]"
    Fee2513_header_11 = "2513 Fee"
    Fee2513_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[11]"
    Fee2513_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[12]"
    Total_header_11 = "Total"
    Total_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[12]"
    Total_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[13]"
    SECFee_header_11 = "SEC Fee"
    SECFee_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[13]"
    SECFee_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[14]"
    TAFFee_header_11 = "TAF Fee"
    TAFFee_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[14]"
    TAFFee_element_12 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[15]"
    IndexUnits_header_11 = "Index Units"
    ETFItems_header_11 = "ETF Items"
    ETFAmount_header_11 = "ETF Amount"
    ETFAmount_element_11 = "//table[@id='ctl00_CC_FeeGridView']/tbody/tr[2]/td[17]"
    ETFItems_header_12 = "ETF_Items"
    ETFAmount_header_12 = "ETF_Amount"

    OfficeCode = "ctl00_CC_OfficeCodeTxt"
    TestOfficeCode = "PO"
    AccountNumber_header_13 = "AccountNumber"
    AccountNumber_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[2]"
    RepCode_header_13 = "RepCode"
    RepCode_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[3]"
    ActivityDate_header_13 = "ActivityDate"
    ActivityDate_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[4]"
    Description_header_13 = "Description"
    Description_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[5]"
    Description2_header_13 = "Description2"
    Source_header_13 = "Source"
    Source_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[7]"
    SourceDescription_header_13 = "SourceDescription"
    SourceDescription_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[8]"
    CreditAmount_header_13 = "CreditAmount"
    CreditAmount_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[9]"
    DebitAmount_header_13 = "DebitAmount"
    DebitAmount_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[10]"
    CostofFunds_header_13 = "CostofFunds"
    CostofFunds_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[11]"
    Balance_header_13 = "Balance"
    Balance_element_13 = "//table[@id='ctl00_CC_DebitInterestGridView']/tbody/tr[2]/td[12]"

    AccountNumber_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th"
    AccountNumber_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td"
    Source_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[2]"
    Source_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[2]"
    RepCode_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[3]"
    RepCode_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[3]"
    AccountTitle_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[4]"
    AccountTitle_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[4]"
    IsActive_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[5]"
    IsActive_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[5]"
    UserName_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[7]"
    UserName_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[7]"
    UpdateDate_header_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr/th[8]"
    UpdateDate_element_14 = "//table[@id='ctl00_CC_GridView1']/tbody/tr[2]/td[8]"

    Month_header_15 = "Month"
    Month_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[2]"
    P3Account_header_15 = "P3 Account"
    P3Account_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[3]"
    P3Sub_header_15 = "P3 Sub"
    P3Sub_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[4]"
    P3Branch_header_15 = "P3 Branch"
    P3Branch_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[5]"
    P3Dept_header_15 = "P3 Dept"
    P3Dept_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[6]"
    Description1_header_15 = "Description1"
    Description1_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[7]"
    Description2_header_15 = "Description2"
    Description2_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[8]"
    Entries_header_15 = "Entries"
    Entries_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[9]"
    Credit_header_15 = "//*[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[1]/th[10]/a"
    Credit_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[10]"
    Debit_header_15 = "Debit"
    Debit_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[11]"
    NetAmount_header_15 = "NetAmount"
    NetAmount_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[12]"
    GPAccount_header_15 = "GP Account"
    GPAccount_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[13]"
    GPBranch_header_15 = "GP Branch"
    GPBranch_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[14]"
    GPDept_header_15 = "GP Dept"
    GPDept_element_15 = "//table[@id='ctl00_CC_GeneralLedgerGridView']/tbody/tr[2]/td[15]"

    SnapshotDate_header_16 = "SnapshotDate"
    SnapshotDate_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[2]"
    PostFullDate_header_16 = "PostFullDate"
    PostFullDate_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[3]"
    P3Account_header_16 = "P3 Account"
    P3Account_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[4]"
    P3Sub_header_16 = "P3 Sub"
    P3Sub_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[5]"
    P3Branch_header_16 = "P3 Branch"
    P3Branch_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[6]"
    P3Dept_header_16 = "P3 Dept"
    P3Dept_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[7]"
    Description_header_16 = "Description"
    Description_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[8]"
    Credit_header_16 = "//*[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[1]/th[9]/a"
    Credit_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[9]"
    Debit_header_16 = "Debit"
    Debit_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[10]"
    GPAccount_header_16 = "GP Account"
    GPAccount_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[11]"
    GPBranch_header_16 = "GP Branch"
    GPBranch_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[12]"
    GPDept_header_16 = "GP Dept"
    GPDept_element_16 = "//table[@id='ctl00_CC_GeneralLedgerDetailGridView']/tbody/tr[2]/td[13]"

    Month_header_17 = "Month"
    Month_element_17 = "//table[@id='ctl00_CC_Phase3DTCAllocationGridView']/tbody/tr[2]/td[2]"
    Office_header_17 = "OFFICE"
    Office_element_17 = "//table[@id='ctl00_CC_Phase3DTCAllocationGridView']/tbody/tr[2]/td[3]"
    Dept_header_17 = "Dept"
    Dept_element_17 = "//table[@id='ctl00_CC_Phase3DTCAllocationGridView']/tbody/tr[2]/td[4]"
    Positions_header_17 = "Positions"
    Positions_element_17 = "//table[@id='ctl00_CC_Phase3DTCAllocationGridView']/tbody/tr[2]/td[5]"
    Allocation_header_17 = "Allocation"
    Allocation_element_17 = "//table[@id='ctl00_CC_Phase3DTCAllocationGridView']/tbody/tr[2]/td[6]"

    AverageNumberChartCSS = "//body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/span[1]/svg[1]/g[8]/text[1]/tspan[1]"
    AccountsPayableChartCSS = "//body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/span[1]/svg[1]/g[8]/text[1]/tspan[1]"
    AverageNumberChart = "//body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/span[1]/svg[1]/g[1]"
    AccountsPayableChart = "//body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/span[1]/svg[1]/g[2]"
    Top10DepartmentsByNo_Title = "//form[@id='aspnetForm']/center/table/tbody/tr[3]/td/div/table/tbody/tr[2]/td/table/tbody/tr/td"
    Top10DepartmentsByNo_col1 = "//table[@id='ctl00_CC_gvDepNumInvoices']/tbody/tr/th"
    Top10DepartmentsByNo_col2 = "//table[@id='ctl00_CC_gvDepNumInvoices']/tbody/tr/th[2]"
    Top10DepartmentsByNo_col3 = "//table[@id='ctl00_CC_gvDepNumInvoices']/tbody/tr/th[3]"
    Top10DepartmentsByNo_col4 = "//table[@id='ctl00_CC_gvDepNumInvoices']/tbody/tr/th[4]"
    Top10UsersByNo_Title = "//form[@id='aspnetForm']/center/table/tbody/tr[3]/td/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td"
    Top10UsersByNo_col1 = "//table[@id='ctl00_CC_gvUsrNumInvoices']/tbody/tr/th"
    Top10UsersByNo_col2 = "//table[@id='ctl00_CC_gvUsrNumInvoices']/tbody/tr/th[2]"
    Top10UsersByNo_col3 = "//table[@id='ctl00_CC_gvUsrNumInvoices']/tbody/tr/th[3]"
    Bottom10Departments_Title = "//form[@id='aspnetForm']/center/table/tbody/tr[3]/td/div/table/tbody/tr[3]/td/table/tbody/tr/td"
    Bottom10Departments_col1 = "//table[@id='ctl00_CC_gvDepBottomAvgProcTime']/tbody/tr/th"
    Bottom10Departments_col2 = "//table[@id='ctl00_CC_gvDepBottomAvgProcTime']/tbody/tr/th[2]"
    Bottom10Departments_col3 = "//table[@id='ctl00_CC_gvDepBottomAvgProcTime']/tbody/tr/th[3]"
    Bottom10Departments_col4 = "//table[@id='ctl00_CC_gvDepBottomAvgProcTime']/tbody/tr/th[4]"
    Bottom10UsersByNo_Title = "//form[@id='aspnetForm']/center/table/tbody/tr[3]/td/div/table/tbody/tr[3]/td[2]/table/tbody/tr/td"
    Bottom10UsersByNo_col1 = "//table[@id='ctl00_CC_gvBotUsrProcTime']/tbody/tr/th"
    Bottom10UsersByNo_col2 = "//table[@id='ctl00_CC_gvBotUsrProcTime']/tbody/tr/th[2]"
    Bottom10UsersByNo_col3 = "//table[@id='ctl00_CC_gvBotUsrProcTime']/tbody/tr/th[3]"
    Top10DepartmentsByInv_Title = "//form[@id='aspnetForm']/center/table/tbody/tr[3]/td/div/table/tbody/tr[4]/td/table/tbody/tr/td"
    Top10DepartmentsByInv_col1 = "//table[@id='ctl00_CC_gvDepInvLiab']/tbody/tr/th"
    Top10DepartmentsByInv_col2 = "//table[@id='ctl00_CC_gvDepInvLiab']/tbody/tr/th[2]"
    Top10DepartmentsByInv_col3 = "//table[@id='ctl00_CC_gvDepInvLiab']/tbody/tr/th[3]"
    Top10DepartmentsByInv_col4 = "//table[@id='ctl00_CC_gvDepInvLiab']/tbody/tr/th[4]"

    IvanOTC_title = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr/td"
    TradeDateFrom_title = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td"
    TradeDateFrom_field = "ctl00_CC_TradeDateTxt"
    TradeDateTo_title = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td[3]"
    TradeDateTo_field = "ctl00_CC_TradeDateToTxt"
    IVANAccNumber_title = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td[5]"
    IVANAccNumber_field = "ctl00_CC_AccountNumberTxt"

    AccountNumber_header_18 = "AccountNumber"
    AccountNumber_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[2]"
    EntitySub_header_18 = "EntitySub"
    EntitySub_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[3]"
    Cusip_header_18 = "CUSIP"
    Cusip_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[4]"
    Symbol_header_18 = "Symbol"
    Symbol_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[5]"
    ProjRunDate_header_18 = "ProjRunDate"
    ProjRunDate_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[6]"
    ProjSettleDate_header_18 = "ProjSettleDate"
    ProjSettleDate_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[7]"
    ProjClose_header_18 = "ProjClosePrice"
    ProjClose_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[8]"
    ProjSettleQty_header_18 = "ProjSettleQty"
    ProjSettleQty_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[9]"
    ProjSettleMkt_header_18 = "ProjSettleMktValue"
    ProjSettleMkt_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[10]"
    ActualSettleDate_header_18 = "ActualSettleDate"
    ActualSettleDate_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[11]"
    ActualClosePrice_header_18 = "ActualClosePrice"
    ActualClosePrice_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[12]"
    ActualSettleQty_header_18 = "ActualSettleQty"
    ActualSettleQty_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[13]"
    ActualSettleMkt_header_18 = "ActualSettleMktValue"
    ActualSettleMkt_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[14]"
    QtyDiff_header_18 = "QtyDifference"
    QtyDiff_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[15]"
    MktValueDiff_header_18 = "MktValueDifference"
    MktValueDiff_element_18 = "//table[@id='ctl00_WG_PabProjectionGridView']/tbody/tr[2]/td[16]"

    monthDropDown = "ctl00_CC_FilterDropDown"
    monthDropDown2 = "ctl00_CC_MonthDpl"
    monthDropDown2List = "//option[contains(text(),'January 2021')]"



