
class CreditPage(object):
    Credit_header = "Credit"
    CreditDashboard_header = "Credit Dashboard"
    CrossGuarantee_header = "Cross Guarantee Report"
    NonPurpose_header = "Non-Purpose"
    P3401Bletters_header = "//a[contains(text(),'P3 401B  Letters')]"
    ShortPosition_header = "Short Position Report"
    TopMarket_header = "Top Market Value Reports"

    SettleDate = "ctl00_CC_runDate"
    SettleDate2 = "ctl00_CC_tbSettleDate"
    SettleDateFrom = "ctl00_CC_SettleDateFromTxt"
    SettleDateTo = "ctl00_CC_SettleDateToTxt"
    ReportDate = "ctl00_CC_ReportDateFromTxt"
    ReportDate2 = "ctl00_CC_ReportDateTxt"
    TradeDate = "ctl00_CC_TradeDateTxt"
    TradeDate2 = "ctl00_CC_tbTradeDate"
    Date = "ctl00_CC_DateTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    CusipTxt = "ctl00_CC_CUSIPTxt"
    CusipAAPL = "AAPL"
    CusipMSFT = "MSFT"
    CusipAMZN = "AMZN"
    SearchButton = "ctl00_CC_SearchBtn"
    SearchButton2 = "ctl00_CC_btnSearch"
    Download_button = "ctl00_CC_DownloadBtn"
    Download_button2 = "ctl00_CC_btnDownload"
    ReportType = "ctl00_CC_ddlReportType"
    TestReportType = "BETA"

    officeChart = "//div[@id='officerChartDiv']"
    officeTable = "//div[@id='ctl00_CC_officerTableUpdate']//table[@id='ctl00_CC_GridView1']"
    CorrOfficeChart = "//div[@id='corChartDiv']"
    CorrOfficeTable = "//div[@id='ctl00_CC_corTableUpdate']//table[@id='ctl00_CC_GridView1']"
    PCSOfficeChart = "//div[@id='myFirstDiv']"
    PCSOfficeTable = "//div[@id='ctl00_CC_pcstableUpdate']//table[@id='ctl00_CC_GridView1']"
    firstTable = "//body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]"

    Guaranteed_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th"
    Guaranteed_element = "//tbody/tr[2]/td[1]/a[1]"
    Name_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[2]"
    Name_element = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr[2]/td[2]"
    GuarantorAcc2_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[3]"
    GuarantorAcc2_element = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr[2]/td[1]"
    GuarantorAcc3_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[4]"
    GuarantorAcc4_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[2]"
    GuarantorAcc5_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[3]"
    GuarantorAcc6_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[7]"
    ReportFreq_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[3]"
    ReportFreq_element = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr[2]/td[8]"

    AccountNumber_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th"
    AccountNumber_element = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr[2]/td"
    AccountName_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[2]"
    AccountName_element = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr[2]/td[2]"
    Edit_header = "//table[@id='ctl00_CC_gvMainReport']/tbody/tr/th[3]"
    AddAccount_tittle = "ctl00_CC_lblAcct"
    AddAccount_field = "ctl00_CC_tbAccountNum"
    AddAccount_button = "ctl00_CC_btnEnter"

    TransactionDate_Title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td"
    TransactionDate_Field = "ctl00_CC_tbTransactionDate"
    EntityCode_Title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[3]"
    EntityCode_Field = "ctl00_CC_tbEntityCode"
    AccountNumber_Title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[5]"
    AccountNumber_Field = "ctl00_CC_tbAccountNumber"
    Note_Title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[7]"
    Note_Field = "ctl00_CC_tbNote"
    P3Save_button = "ctl00_CC_btSave"
    P3Search_button = "ctl00_CC_btnSearch"
    P3Download_button = "ctl00_CC_btnDownload"
    P3401b_Title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td"

    OfficeDivision_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_OfficeDivision_LinkButton"
    OfficeDivision_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_OfficeDivisionLabel"
    AccountNumber_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_AccountNumber_LinkButton"
    AccountNumber_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_AccountNumberLabel"
    AccountType_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_AccountType_LinkButton"
    AccountType_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_AccountTypeLabel"
    Name_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_Name_LinkButton"
    Name_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_NameLabel"
    Symbol_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_Symbol_LinkButton"
    Symbol_element_1 = "//table[@id='ctl00_WG_ShortPositionReportGridView']/tbody/tr[2]/td[6]"
    Cusip_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_CUSIPLabel"
    Quantity_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_Quantity_LinkButton"
    Quantity_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_QuantityLabel"
    MarketValue_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_MarketValue_LinkButton"
    MarketValue_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_MarketValueLabel"
    AccountEquity_header_1 = "ctl00_WG_ShortPositionReportGridView_ctl01_AccountEquity_LinkButton"
    AccountEquity_element_1 = "ctl00_WG_ShortPositionReportGridView_ctl02_AccountEquityLabel"

    Symbol_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_Symbol_LinkButton"
    Symbol_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_SymbolLabel"
    Cusip_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_Cusip_LinkButton"
    Cusip_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_CusipLabel"
    Description_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_Description_LinkButton"
    MarginElig_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_MarginElig_LinkButton"
    MarginElig_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_MarginEligLabel"
    MarketPrice_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_MarketPrice_LinkButton"
    MarketPrice_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_MarketPriceLabel"
    Quantity_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_Quantity_LinkButton"
    Quantity_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_QuantityLabel"
    LMV_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_MV_LinkButton"
    LMV_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_MVLabel"
    FiveDay_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_FiveDayAvgVolume_LinkButton"
    FiveDay_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_FiveDayAvgVolumeLabel"
    QtyFiveDay_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_Qty5DayAvgVol_LinkButton"
    QtyFiveDay_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_Qty5DayAvgVolLabel"
    MarketCap_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_MarketCap_LinkButton"
    MarketCap_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_MarketCapLabel"
    MarketCapPct_header_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl01_MarketCapPct_LinkButton"
    MarketCapPct_element_2 = "ctl00_WG_TopMarketValueReportsGridView_ctl02_MarketCapPctLabel"



