
class CSDOperationsPage(object):
    CSDOperations_header = "CSD Operations"
    Deposit_header = "Correspondent Deposit vs Required Deposit"
    Focus_header = "Correspondent Focus Monitoring"
    Billing_header = "Correspondent Billing"
    Billing_Detail_header = "Correspondent Billing Detail"

    SettleDate = "ctl00_CC_SettleDateTxt"
    SettleDate2 = "ctl00_CC_tbSettleDate"
    SettleDateFrom = "ctl00_CC_SettleDateFromTxt"
    SettleDateTo = "ctl00_CC_SettleDateToTxt"
    ReportDate = "ctl00_CC_ReportDateFromTxt"
    ReportDate2 = "ctl00_CC_ReportDateTxt"
    TradeDate = "ctl00_CC_TradeDateTxt"
    TradeDate2 = "ctl00_CC_tbTradeDate"
    Date = "ctl00_CC_DateTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    CusipTxt = "ctl00_CC_CUSIPTxt"
    CusipAAPL = "AAPL"
    CusipMSFT = "MSFT"
    CusipAMZN = "AMZN"
    SearchButton = "ctl00_CC_SearchBtn"
    SearchButton2 = "ctl00_CC_btnSearch"
    Download_button = "ctl00_CC_DownloadBtn"
    Download_button2 = "ctl00_CC_btnDownload"

    AccountNumber_header_1 = "AccountNumber"
    AccountNumber_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[2]"
    RepCode_header_1 = "RepCode"
    RepCode_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[3]"
    CSI_header_1 = "CSI"
    CSI_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[4]"
    NameLine1_header_1 = "NameLine1"
    NameLine1_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[5]"
    OpenDate_header_1 = "OpenDate"
    OpenDate_elementr_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[6]"
    Balance_header_1 = "Balance"
    Balance_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[7]"
    ReqDeposit_header_1 = "RequiredDeposit"
    ReqDeposit_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[8]"
    LongMarket_header_1 = "LongMarketValue"
    LongMarket_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[9]"
    ShorMarket_header_1 = "ShortMarketValue"
    ShorMarket_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[10]"
    Equity_header_1 = "Equity"
    Equity_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[11]"
    TotalValue_header_1 = "TotalValue"
    TotalValue_element_1 = "//table[@id='ctl00_CC_CorrespondentdepositGridView']/tbody/tr[2]/td[12]"

    AsofDate_header_2 = "AsofDate"
    AsofDate_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[2]"
    FirmName_header_2 = "FirmName"
    FirmName_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[3]"
    FirmID_header_2 = "FirmID"
    FirmID_element_2 = "//td[4]/a"
    Freq_header_2 = "Freq"
    Freq_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[5]"
    Method_header_2 = "Method"
    Method_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[6]"
    Requirement_header_2 = "Requirement"
    Requirement_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[7]"
    PreviousNet_header_2 = "Previous Net Capital"
    PreviousNet_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[8]"
    CurrentNet_header_2 = "Current Net Capital"
    CurrentNet_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[9]"
    Change_header_2 = "% Change"
    Change_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[10]"
    ExcessNet_header_2 = "Excess Net Capital"
    ExcessNet_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[11]"
    NetIncome_header_2 = "Net Income"
    NetIncome_element_2 = "//table[@id='ctl00_CC_CorrespondentFocusMonitoringGridView']/tbody/tr[2]/td[12]"
    Exception_header_2 = "Exception"

    Month_header_3 = "Month"
    Month_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[2]"
    EntityCode_header_3 = "Entity Code"
    EntityCode_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[3]"
    EntityName_header_3 = "Entity Name"
    Commission_header_3 = "Commission"
    Commission_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[5]"
    ClearingFee_header_3 = "Clearing Fee"
    ClearingFee_element_3 = "//td[6]/a"
    MonthlyMin_header_3 = "Monthly Minimum"
    MonthlyMin_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[7]"
    Payout_header_3 = "Payout"
    Payout_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[8]"
    Postage_header_3 = "Postage Fee"
    Postage_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[9]"
    ECNTake_header_3 = "ECN TakeLiquidity Fee"
    ECNTake_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[10]"
    ECNAdd_header_3 = "ECN AddLiquidity Fee"
    ECNAdd_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[11]"
    ORFFee_header_3 = "ORF Fee"
    ORFFee_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[12]"
    SecFee_header_3 = "Sec Fee"
    SecFee_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[14]"
    TradeCount_header_3 = "Trade Count"
    TradeCount_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[15]"
    EquityVolume_header_3 = "Equity Volume"
    EquityVolume_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[16]"
    OptionsVolume_header_3 = "Options Volume"
    OptionsVolume_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[17]"
    FixedIncome_header_3 = "Fixed Income Volume"
    FixedIncome_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[18]"
    PB_header_3 = "PB Comm"
    PB_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[19]"
    TAFFee_header_3 = "TAF Fee"
    TAFFee_element_3 = "//table[@id='ctl00_CC_CorrespondentBillingGridView']/tbody/tr[2]/td[13]"

    EntryDate_header_4 = "Entry Date"
    EntryDate_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[2]"
    ContractID_header_4 = "Contract ID"
    ContractID_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[3]"
    DetailID_header_4 = "Detail ID"
    DetailID_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[4]"
    ContractCode_header_4 = "Contract Code"
    ContractCode_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[5]"
    ContractDetail_header_4 = "Contract Detail Description"
    ContractDetail_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[6]"
    MinTicket_header_4 = "Min Ticket"
    MinTicket_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[7]"
    MaxTicket_header_4 = "Max Ticket"
    MaxTicket_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[8]"
    MinShare_header_4 = "Min Share"
    MinShare_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[9]"
    MaxShare_header_4 = "Max Share"
    MaxShare_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[10]"
    TicketTradeQty_header_4 = "Ticket Trade Qty"
    TicketTradeQty_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[11]"
    TicketTradeCount_header_4 = "Ticket Trade Count"
    TicketTradeCount_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[12]"
    PerTicket_header_4 = "Per Ticket Rate"
    PerTicket_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[13]"
    ShareTradeCount_header_4 = "Share Trade Count"
    ShareTradeQty_header_4 = "Share Trade Qty"
    PerShare_header_4 = "Per Share Rate"
    PerShare_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[16]"
    MinRate_header_4 = "Min Rate"
    MinRate_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[18]"
    MaxRate_header_4 = "Max Rate"
    MaxRate_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[19]"
    ShareTrade_header_4 = "Share Trade Qty Not Max"
    ClearingFee_header_4 = "Clearing Fee"
    ClearingFee_element_4 = "//table[@id='ctl00_CC_CorrespondentBillingDetailGridView']/tbody/tr[2]/td[21]"
    ShareMaxTicket_header_4 = "Share Max Ticket"

    txtDate = "ctl00_CC_txtDate"
    datePicker_5 = "//div[@id='ui-datepicker-div']/div/a/span"

