
class LoginPage(object):
    testuser = "islaso"
    testpassw = "Nov@2020!"
    testpacc = "80759001"
    testemail = "octavio.islas@wedbush.com"
    header = "//form[@id='aspnetForm']/center/table/tbody/tr/td/table/tbody/tr/td/a/span"
    borrowloan_header = "Borrow Loan"
    Sttlement_header = "Settlement"
    CSDOperations_header = "CSD Operations"
    FPL_header = "FPL"
    Phase3_header = "Phase3"
    Compliance_header = "Compliance"
    Credit_header = "Credit"
    Accounting_header = "Accounting"
    Phase3FIX_header = "Phase3 FIX"
    NewAccounts_header = "New Accounts"
    WealthMgmt_header = "Wealth Management"
    Treasury_header = "Treasury"
