
class Phase3FIXPage(object):
    Phase3FIX_header = "Phase3 FIX"
    TradexFiles_header = "Tradex Files"
    TimeTickFiles_header = "TimeTick Files"
    WTPReal_header = "WTP Real-time FIX Engine"
    WCETems_header = "WCE TEMS Real-time FIX Engine"
    Documents_header = "Documents"
    FIXTags_header = "FIX Tags"
    DIVADJStatus_header = "DIVADJ Upload Status"
    DIVADJUpload_header = "DIVADJ Upload"
    P3ETFBreak_header = "P3 ETF Create Redeem Break Report"
    P3ETFRedeem_header = "P3 ETF Create Redeem NSCC Clearance"
    WTPTrue_header = "WTP RealTime True Pending"

    SettleDate = "ctl00_CC_runDate"
    SettleDate2 = "ctl00_CC_tbSettleDate"
    SettleDateFrom = "ctl00_CC_SettleDateFromTxt"
    SettleDateTo = "ctl00_CC_SettleDateToTxt"
    SearchButton = "ctl00_CC_SearchBtn"
    ActualDate = "ctl00_CC_DateFromTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    WedbushFixEnginePage = "Wedbush RealTime Fix Engine UAT"
    TradeExceptionPage = "Trade Exception Manager"
    FIXTagsPage = "FIX 4.4: Fields by Tag – FIX Dictionary – Onix Solutions"

    FileDate_header_1 = "ctl00_CC_P3FixGridView_ctl02_FileDate_LinkButton"
    FileDate_element_1 = "ctl00_CC_P3FixGridView_ctl03_FileDateLabel"
    FileName_header_1 = "ctl00_CC_P3FixGridView_ctl02_FileName_LinkButton"
    FileName_element_1 = "ctl00_CC_P3FixGridView_ctl03_FileNameLabel"
    FileRawRow_header_1 = "ctl00_CC_P3FixGridView_ctl02_FileRawRow_LinkButton"
    FileRawRow_element_1 = "ctl00_CC_P3FixGridView_ctl03_FileRawRowLabel"
    IngestError_header_1 = "ctl00_CC_P3FixGridView_ctl02_IngestError_LinkButton"
    TotalRows_header_1 = "ctl00_CC_P3FixGridView_ctl02_TotalRows_LinkButton"
    TotalRows_element_1 = "ctl00_CC_P3FixGridView_ctl03_TotalRowsLabel"
    Pending_header_1 = "ctl00_CC_P3FixGridView_ctl02_Pending_LinkButton"
    Success_header_1 = "ctl00_CC_P3FixGridView_ctl02_Success_LinkButton"
    Reject_header_1 = "ctl00_CC_P3FixGridView_ctl02_Reject_LinkButton"
    FixCompleted_header_1 = "ctl00_CC_P3FixGridView_ctl02_FixCompleted_LinkButton"
    FixCompleted_element_1 = "ctl00_CC_P3FixGridView_ctl03_FixCompletedLabel"
    CancelPending_header_1 = "ctl00_CC_P3FixGridView_ctl02_CancelPending_LinkButton"
    CancelSuccess_header_1 = "ctl00_CC_P3FixGridView_ctl02_CancelSuccess_LinkButton"
    CancelReject_header_1 = "ctl00_CC_P3FixGridView_ctl02_CancelReject_LinkButton"
    CxlCompleted_header_1 = "ctl00_CC_P3FixGridView_ctl02_CxlCompleted_LinkButton"
    FixFile_header_1 = "ctl00_CC_P3FixGridView_ctl02_FixFileID_LinkButton"
    FixFile_element_1 = "ctl00_CC_P3FixGridView_ctl03_FixFileIDLabel"
    ImportFile_header_1 = "ctl00_CC_P3FixGridView_ctl02_ImportFileId_LinkButton"
    ImportFile_element_1 = "ctl00_CC_P3FixGridView_ctl03_ImportFileIdLabel"
    EntityCode_header_1 = "ctl00_CC_P3FixGridView_ctl02_EntityCode_LinkButton"
    EntityCode_element_1 = "ctl00_CC_P3FixGridView_ctl03_EntityCodeLabel"
    FTP_header_1 = "ctl00_CC_P3FixGridView_ctl02_FTP_LinkButton"
    UpdateDate_header_1 = "ctl00_CC_P3FixGridView_ctl02_UpdateDateTime_LinkButton"
    UpdateDate_element_1 = "ctl00_CC_P3FixGridView_ctl03_UpdateDateTimeLabel"

    DateFrom_title_1 ="//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td"
    DateFrom_field_1 = "ctl00_CC_DateFromTxt"
    DateTo_title_1 = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td[3]"
    DateTo_field_1 = "ctl00_CC_DateToTxt"
    FileName_title_1 = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td[5]"
    FileName_field_1 = "ctl00_CC_FileNameTxt"
    Download_button_1 = "ctl00_CC_DownloadBtn"

    DocWTPEngineFIXSessions = "WTP Engine FIX Sessions List"
    PageWTPEngineFIXSessions = "WTP Engine FIX Sessions List.pdf"
    DocWCE_Correspondents = "WCE_CorrespondentsSupportContacts"
    PageWCE_Correspondents = "WCE_CorrespondentsSupportContacts.pdf"
    DocWCECorrespondents = "WCE Correspondents Support Contacts"
    PageWCECorrespondents = "WCE Correspondents Support Contacts.pdf"
    DocTradeCaptureTechnical = "Trade Capture Technical Guide - New Customer or Prop Firm v1"
    PageTradeCaptureTechnical = "Trade Capture Technical Guide - New Customer or Prop Firm v1.pdf"
    DocITProduction = "IT Production Support Escalation Contact List"
    PageITProduction = "IT Production Support Escalation Contact List.pdf"
    DocFISWedbush = "FIS Wedbush Escalation Document"
    PageFISWedbush = "FIS Wedbush Escalation Document.pdf"

    Date_Title_2 = "//div[@id='ctl00_WG_InfoPanel']/table/tbody/tr[2]/td"
    Date_field_2 = "ctl00_WG_DateFromTxt"
    DivadStatusTitle = "//div[@id='ctl00_WG_InfoPanel']/table/tbody/tr/td"
    SearchButton_2 = "ctl00_WG_SearchBtn"

    DragDropSpace = "//div[@id='box']/div"
    SubmitFiles_button = "ctl00_WG_SubmitBtn"
    Upload_button = "upload"
    UpdateStatus_button = "ctl00_WG_UpdateStatusBtn"

    TradeDate_header_2 = "Trade Date"
    TradeDate_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[2]"
    SettleDate_header_2 = "Settle Date"
    SettleDate_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[3]"
    SecurityType_header_2 = "Security Type"
    SecurityType_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[4]"
    Cusip_header_2 = "CUSIP"
    Cusip_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[5]"
    Symbol_header_2 = "Symbol"
    Symbol_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[6]"
    DebitCredit_header_2 = "Debit/Credit"
    DebitCredit_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[7]"
    BuySell_header_2 = "Buy/Sell"
    BuySell_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[8]"
    UnitQuantity_header_2 = "Unit Quantity"
    UnitQuantity_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[9]"
    SharesPerUnit_header_2 = "Shares per Unit"
    SharesPerUnit_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[10]"
    NSCCQuantity_header_2 = "NSCC Quantity"
    NSCCQuantity_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[11]"
    NSCCPrice_header_2 = "NSCC Price"
    NSCCPrice_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[12]"
    NSCCAmount_header_2 = "NSCC Amount"
    NSCCAmount_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[13]"
    TradeSymbol_header_2 = "TradeSymbol"
    TradeSymbol_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[14]"
    TradeBuy_header_2 = "Trade Buy Sell"
    TradeBuy_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[15]"
    TradeQuantity_header_2 = "Trade Quantity"
    TradeQuantity_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[16]"
    TradeAmount_header_2 = "Trade Amount"
    TradeAmount_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[17]"
    TradePrice_header_2 = "Trade Price"
    TradePrice_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[18]"
    QuantityDiff_header_2 = "Quantity Diff"
    QuantityDiff_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[19]"
    AmountDiff_header_2 = "Amount Diff"
    AmountDiff_element_2 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[20]"

    TradeDate_header_3 = "TradeDate"
    TradeDate_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[2]"
    SettleDate_header_3 = "SettleDate"
    SettleDate_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[3]"
    ETF_header_3 = "ETF"
    ETF_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[4]"
    Cusip_header_3 = "CUSIP"
    Cusip_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[5]"
    Symbol_header_3 = "Symbol"
    Symbol_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[6]"
    CR_header_3 = "C/R"
    BuySell_header_3 = "BuySell"
    BuySell_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[8]"
    UnitQuantity_header_3 = "UnitQty"
    UnitQuantity_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[9]"
    SharesPerUnit_header_3 = "SharesPerUnit"
    SharesPerUnit_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[10]"
    NSCCQuantity_header_3 = "NSCCQuantity"
    NSCCQuantity_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[11]"
    NSCCPrice_header_3 = "NSCCPrice"
    NSCCPrice_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[12]"
    NSCCSettleAmount_header_3 = "NSCCSettleAmount"
    NSCCSettleAmount_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[13]"
    DebitCredit_header_3 = "DebitCredit"
    DebitCredit_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[14]"
    Contra_header_3 = "Contra"
    CashAmount_header_3 = "CashAmount"
    CashAmount_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[16]"
    ComponentSettle_header_3 = "ComponentSettleValue"
    ComponentSettle_elementr_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[17]"
    TransactionFee_header_3 = "TransactionFee"
    Cycle_header_3 = "Cycle"
    Cycle_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[19]"
    TransactionId_header_3 = "TransactionId"
    TransactionId_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[20]"
    PortfolioId_header_3 = "PortfolioId"
    PortfolioId_element_3 = "//table[@id='ctl00_CC_P3ETFNSCCClearanceGridView']/tbody/tr[3]/td[21]"
    UpdateDate_header_3 = "UpdateDateTime"

    WTPRealTime_title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td/table/tbody/tr/td"
    TradeDate_title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td/table/tbody/tr[2]/td"
    TradeDate_field = "ctl00_CC_DateFromTxt"
    Symbol_title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[3]"
    Symbol_field = "ctl00_CC_SymbolTxt"
    AccountNumber_title = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td/table/tbody/tr[2]/td[5]"
    AccountNumber_field = "ctl00_CC_AccountTxt"
    Download_button_2 = "ctl00_CC_DownloadBtn"
    Trade_button = "ctl00_CC_TradexBtn"


