
class Phase3Page(object):
    Phase3_header = "Phase3"
    P3TradeBlotter_header = "P3 Trade Blotter"
    P3StockRecord_header = "P3 Stock Record"
    P3CashActivity_header = "P3 Cash Activity"
    P3StockMovement_header = "P3 Stock Movement"
    P3AccountInf_header = "P3 Account Information"
    P3SecurityMaster_header = "P3 Security Master"
    P3Verification_header = "P3 Verification Of Assets"

    SettleDate = "ctl00_CC_SettleDateTxt"
    SettleDate2 = "ctl00_CC_tbSettleDate"
    SettleDateFrom = "ctl00_CC_SettleDateFromTxt"
    SettleDateTo = "ctl00_CC_SettleDateToTxt"
    ReportDate = "ctl00_CC_ReportDateFromTxt"
    ReportDate2 = "ctl00_CC_ReportDateTxt"
    TradeDate = "ctl00_CC_DateFromTxt"
    TradeDate2 = "ctl00_CC_tbTradeDate"
    Date = "ctl00_CC_DateTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    CusipTxt = "ctl00_CC_CUSIPtxt"
    Cusip = "ctl00_CC_CUSIPTxt"
    CusipAAPL = "AAPL"
    CusipMSFT = "MSFT"
    CusipAMZN = "AMZN"
    CusipSBNYP = "SBNYP"
    SearchButton = "ctl00_CC_SearchBtn"
    SearchButton2 = "ctl00_CC_btnSearch"
    Download_button = "ctl00_CC_DownloadBtn"
    Download_button2 = "ctl00_CC_btnDownload"

    AccountNumber_header_1 = "AccoutNumber"
    AccountNumber_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[2]"
    AcctType_header_1 = "AcctType"
    AcctType_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[3]"
    NameLine1_header_1 = "NameLine1"
    NameLine2_header_1 = "NameLine2"
    NameLine3_header_1 = "NameLine3"
    AcctClass_header_1 = "AcctClass"
    AcctClass_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[7]"
    RepCode_header_1 = "RepCode"
    RepCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[8]"
    RepName_header_1 = "RepName"
    Office_header_1 = "Office"
    Office_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[10]"
    BuySell_header_1 = "BuySell"
    BuySell_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[11]"
    Cusip_header_1 = "CUSIP"
    Cusip_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[12]"
    Symbol_header_1 = "Symbol"
    Symbol_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[13]"
    SecurityDesc_header_1 = "SecurityDesc"
    SecurityDesc_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[14]"
    SecType_header_1 = "SecType"
    SecType_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[15]"
    MktCode_header_1 = "MktCode"
    MktCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[16]"
    TranNbr_header_1 = "TranNbr"
    TranNbr_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[17]"
    Capacity_header_1 = "Capacity"
    Capacity_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[18]"
    LegendCode_header_1 = "LegendCode"
    Quantity_header_1 = "Quantity"
    Quantity_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[20]"
    Price_header_1 = "Price"
    Price_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[21]"
    Principal_header_1 = "Principal"
    Principal_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[22]"
    GrossCommission_header_1 = "GrossCommission"
    GrossCommission_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[23]"
    HandlingFee_header_1 = "HandlingFee"
    HandlingFee_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[24]"
    TakerLiquid_header_1 = "TakerLiquidityFee"
    TakerLiquid_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[25]"
    MarketLiquid_header_1 = "MakerLiquidityFee"
    MarketLiquid_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[26]"
    ORFFee_header_1 = "ORF_Fee"
    ORFFee_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[27]"
    TAFFee_header_1 = "TAF_Fee"
    TAFFee_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[28]"
    SecFeeAmount_header_1 = "SecFeeAmount"
    SecFeeAmount_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[29]"
    TradeInterest_header_1 = "TradeInterest"
    TradeInterest_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[30]"
    NetAmount_header_1 = "NetAmount"
    NetAmount_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[31]"
    TradeDate_header_1 = "TradeDate"
    TradeDate_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[32]"
    SettleDate_header_1 = "SettleDate"
    SettleDate_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[33]"
    ExecTime_header_1 = "ExecTime_Est"
    ExecTime_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[34]"
    EntryDate_header_1 = "EntryDate"
    EntryDate_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[35]"
    EntryTime_header_1 = "EntryTime_Est"
    EntryTime_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[36]"
    SeqNbr_header_1 = "SeqNbr"
    SeqNbr_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[37]"
    ProductCode_header_1 = "ProductCode"
    ProductCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[38]"
    FrontExec_header_1 = "FrontExec"
    FrontExec_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[39]"
    BackExec_header_1 = "BackExec"
    BackExec_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[40]"
    ContraAccount_header_1 = "ContraAccount"
    ContraAccount_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[41]"
    Cancelled_header_1 = "Cancelled"
    Cancelled_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[42]"
    RebilledTrade_header_1 = "RebilledTrade"
    CommissionType_header_1 = "CommissionType"
    RRNETCOMM_header_1 = "RR_NET_COMMISSION"
    RRNETCOMM_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[45]"
    EnteredBy_header_1 = "EnteredBy"
    EnteredBy_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[46]"
    DestCode_header_1 = "DestCode"
    DestCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[47]"
    SpecInstruc1_header_1 = "SpecInstruct1"
    SpecInstruc1_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[48]"
    SpecInstruc2_header_1 = "SpecInstruct2"
    SpecInstruc2_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[49]"
    Trailer_header_1 = "Trailer"
    Trailer_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[50]"
    TrailerCode_header_1 = "TrailerCode"
    TrailerCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[51]"
    GroupCode_header_1 = "GroupCode"
    GroupCode_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[52]"
    Currency_header_1 = "Currency"
    Currency_element_1 = "//table[@id='ctl00_CC_P3TradeBlotterGridView']/tbody/tr[3]/td[53]"

    EntryDate_header_2 = "EntryDate"
    EntryDate_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[2]"
    AcctName_header_2 = "AcctName"
    OfficeRR_header_2 = "OfficeRR"
    OfficeRR_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[4]"
    AcctNbr_header_2 = "AcctNbr"
    AcctNbr_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[5]"
    AcctType_header_2 = "AcctType"
    AcctType_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[6]"
    Cusip_header_2 = "CUSIP"
    Cusip_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[7]"
    Symbol_header_2 = "Symbol"
    TDQuantity_header_2 = "T/D Quantity"
    TDQuantity_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[9]"
    SDQuantity_header_2 = "S/D Quantity"
    SDQuantity_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[10]"
    Currency_header_2 = "Currency"
    Currency_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[11]"
    Location_header_2 = "Location"
    Location_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[12]"
    LastActivityDate_header_2 = "LastActivityDate"
    LastActivityDate_element_2 = "//table[@id='ctl00_CC_P3StockRecordGridView']/tbody/tr[3]/td[13]"

    AcctNbr_header_3 = "AcctNbr"
    AcctNbr_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[2]"
    AcctName_header_3 = "AcctName"
    AcctType_header_3 = "AcctType"
    AcctType_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[4]"
    Cusip_header_3 = "CUSIP"
    EntryDate_header_3 = "EntryDate"
    EntryDate_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[6]"
    TradeDate_header_3 = "TradeDate"
    TradeNbr_header_3 = "TradeNbr"
    SeqNbr_header_3 = "SeqNbr"
    SeqNbr_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[9]"
    RecType_header_3 = "RecType"
    RecType_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[10]"
    Office_header_3 = "Office"
    Office_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[11]"
    Currency_header_3 = "Currency"
    Currency_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[12]"
    Amount_header_3 = "Amount"
    Amount_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[13]"
    Price_header_3 = "Price"
    Price_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[14]"
    Description_header_3 = "Description"
    EntryType_header_3 = "EntryType"
    EntryType_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[16]"
    BankName_header_3 = "BankName"
    Source_header_3 = "Source"
    Source_element_3 = "//table[@id='ctl00_CC_P3CashActivityGridView']/tbody/tr[3]/td[17]"
    BankNumber_header_3 = "BankABANumber"
    BenefName_header_3 = "BeneficiaryName"
    BenefNumber_header_3 = "BeneficiaryAccountNumber"
    FurtherName_header_3 = "FurtherCreditAccountName"
    FurtherNumber_header_3 = "FurtherCreditAccountNumber"

    AcctNbr_header_4 = "AcctNbr"
    AcctNbr_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[2]"
    AcctName_header_4 = "AcctName"
    AcctType_header_4 = "AcctType"
    AcctType_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[4]"
    Cusip_header_4 = "CUSIP"
    Cusip_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[5]"
    Symbol_header_4 = "Symbol"
    SecType_header_4 = "SecType"
    SecType_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[7]"
    Qty_header_4 = "Qty"
    Qty_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[8]"
    EntryDate_header_4 = "EntryDate"
    EntryDate_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[9]"
    TradeDate_header_4 = "TradeDate"
    TradeNbr_header_4 = "TradeNbr"
    SettleDate_header_4 = "SettleDate"
    Trailer_header_4 = "Trailer"
    TSBasis_header_4 = "TSBasis"
    TSBasis_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[14]"
    Office_header_4 = "Office"
    Office_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[15]"
    Source_header_4 = "Source"
    Source_element_4 = "//table[@id='ctl00_CC_P3StockMovementGridView']/tbody/tr[3]/td[16]"

    AcctNbr_header_5 = "AcctNbr"
    AcctNbr_element_5 = "//table[@id='ctl00_CC_P3AccountInfoGridView']/tbody/tr[3]/td[2]"
    AcctName_header_5 = "AcctName"
    AcctClass_header_5 = "AcctClass"
    Office_header_5 = "Office"
    Office_element_5 ="//table[@id='ctl00_CC_P3AccountInfoGridView']/tbody/tr[3]/td[5]"
    Rep_header_5 = "Rep"
    TaxID_header_5 = "TaxID"
    Foreign_header_5 = "Foreign"
    Address1_header_5 = "Address1"
    Address2_header_5 = "Address2"
    City_header_5 = "City"
    State_header_5 = "State"
    Zip_header_5 = "Zip"
    Margin_header_5 = "Margin"
    Option_header_5 = "Option"
    SegCode_header_5 = "SegCode"
    OpenDate_header_5 = "OpenedDate"
    OpenDate_element_5 = "//table[@id='ctl00_CC_P3AccountInfoGridView']/tbody/tr[3]/td[17]"
    RestDate_header_5 = "RestrDate"
    RestReason_header_5 = "RestrReason"

    Cusip_header_6 = "Cusip"
    Cusip_element_6 = "//table[@id='ctl00_WG_SecurityMasterGrid']/tbody/tr[2]/td[2]"
    Symbol_header_6 = "Symbol"
    Symbol_element_6 = "//table[@id='ctl00_WG_SecurityMasterGrid']/tbody/tr[2]/td[3]"
    Desc1_header_6 = "Desc1"
    Desc2_header_6 = "Desc2"
    LastChange_header_6 = "LastChange"
    LastChange_element_6 = "//table[@id='ctl00_WG_SecurityMasterGrid']/tbody/tr[2]/td[6]"
    SecType_header_6 = "SecType"
    SecType_element_6 = "//table[@id='ctl00_WG_SecurityMasterGrid']/tbody/tr[2]/td[7]"
    SecSub_header_6 = "SecSub"
    SecSub_element_6 = "//table[@id='ctl00_WG_SecurityMasterGrid']/tbody/tr[2]/td[8]"
    SectTypDesc_header_6 = "SecTypeDescription"
    Accrue_header_6 = "AccrueAccrete"
    Margin_header_6 = "MarginElig"
    SnP_header_6 = "SnP"
    Moody_header_6 = "Moody"
    IssueDate_header_6 = "IssueDate"
    MaturityDate_header_6 = "MaturityDate"
    BaseRate_header_6 = "BaseRate"
    CouponCode_header_6 = "CouponCode"
    CouponDate_header_6 = "CouponDate"
    FirstCoupon_header_6 = "FirstCouponDate"

    SnapShotDate_header_7 = "SnapShotDate"
    SnapShotDate_element_7 = "//table[@id='ctl00_CC_P3VerificationOfAssetsGridView']/tbody/tr[3]/td[2]"
    AccountNumber_header_7 = "AccountNumber"
    AccountNumber_element_7 = "//table[@id='ctl00_CC_P3VerificationOfAssetsGridView']/tbody/tr[3]/td[3]"
    AccountName_header_7 = "AccountName"
    AcctClass_header_7 = "AcctClass"
    EntityCode_header_7 = "EntityCode"
    EntityCode_element_7 = "//table[@id='ctl00_CC_P3VerificationOfAssetsGridView']/tbody/tr[3]/td[6]"
    RepCode_header_7 = "Repcode"
    RepCode_element_7 = "//table[@id='ctl00_CC_P3VerificationOfAssetsGridView']/tbody/tr[3]/td[7]"
    CashBalance_header_7 = "CashBalance"
    MarginBalance_header_7 = "MarginBalance"
    MarginCredit_header_7 = "MarginCredit"
    MarginDebit_header_7 = "MarginDebit"
    TotalBalance_header_7 = "TotalBalance"
    MarketValue_header_7 = "MarketValue"
    TotalEquity_header_7 = "TotalEquity"
    LongMarket_header_7 = "LongMarketValue"
    ShortMarket_header_7 = "ShortMarketValue"
    Addr1e_header_7 = "Addr1"
    Addr2_header_7 = "Addr2"
    Addr3_header_7 = "Addr3"
    Addr4_header_7 = "Addr4"
    City_header_7 = "City"
    State_header_7 = "State"
    Zip_header_7 = "Zip"
    PhoneType1_header_7 = "PhoneType1"
    Telephone1_header_7 = "Telephone1"
    PhoneType2_header_7 = "PhoneType2"
    Telephone2_header_7 = "Telephone2"
    Email_header_7 = "Email"
    Ownership_header_7 = "Ownership Type (INST)"
    AccountCategory_header_7 = "Account Category"
    DOB_header_7 = "DOB"
    Options_header_7 = "Options"
    InvestmentObjetive_header_7 = "Investment Objective"
    OptionInvestment_header_7 = "Option Investment Objective"
    RiskTolerance_header_7 = "Risk Tolerance"
    NetWorth_header_7 = "Net Worth"
    DateOpened_header_7 = "Date Opened"
    DateClosed_header_7 = "Date Closed"
    BranchId_header_7 = "Branch Identifier"
    BranchId_element_7 = "//table[@id='ctl00_CC_P3VerificationOfAssetsGridView']/tbody/tr[3]/td[39]"
    TaxBracket_header_7 = "Tax Bracket"
    Income_header_7 = "Income"
    LiquidNet_header_7 = "Liquid Net Worth"
    InvestemntAd_header_7 = "Investment Advisor / Fee-Based Account Flag"

