
class SettlementPage(object):
    settlement_header = "Settlement"
    DTCDelivery_header = "DTC Delivery Orders"
    DTCMemo_header = "DTC Memo Seg Submission"
    CNSFails_header = "CNS Fails Beta"
    CNSDelivers_header = "CNS Consecutive Fail To Delivers Beta"
    CNSReceives_header = "CNS Consecutive Fail To Receives Beta"
    StockRecord_header = "Stock Record"
    FailRecord_header = "Fail Record"
    ReleaseBank_header = "Release Bank Collateral Submission"
    SmartLoan_header = "Smart Loan BankLoan Bookkeeping Submission"
    NSCCRequirement_header = "NSCC Clearing Fund Requirement"
    NSCCFirm_header = "NSCC Clearing Fund Requirement By Firm"
    NSCCEquities_header = "NSCC Clearing Fund Requirement By Wedbush Equities"
    Deficit_header = "Deficit Tracking"
    OCCPosition_header = "OCC Position Comparison"
    OperationsAcc_header = "Operations Account Balance Edit Tool"
    CanaccordTrade_header = "Canaccord Trade Report"
    CanaccordDividend_header = "Canaccord Dividend Reports"
    ETFMGOrderDetail_header = "ETFMG Creation/Redemption Order Detail"
    ETFMGOrderSummary_header = "ETFMG Creation/Redemption Order Summary"
    ETFMGCollateral_header = "ETFMG Collateral Summary"
    ETFMGCollDetails_header = "ETFMG Collateral Details"
    ETFOrder_header = "ETF Order Entry"
    RecapReport_header = "Recap Report"
    Unallocated_header = "Unallocated Borrow Cost"
    LargeCustomer_header = "Large Customer Buys"

    SettleDate = "ctl00_CC_SettleDateTxt"
    SettleDate2 = "ctl00_CC_tbSettleDate"
    SettleDateFrom = "ctl00_CC_SettleDateFromTxt"
    SettleDateTo = "ctl00_CC_SettleDateToTxt"
    ReportDate = "ctl00_CC_ReportDateFromTxt"
    ReportDate2 = "ctl00_CC_ReportDateTxt"
    TradeDate = "ctl00_CC_TradeDateTxt"
    TradeDate2 = "ctl00_CC_tbTradeDate"
    Date = "ctl00_CC_DateTxt"
    DateFrom = "ctl00_CC_DateFromTxt"
    SnapshotDate = "ctl00_CC_SnapshotDateTxt"
    DatePiker = "//div[@id='ui-datepicker-div']/div/a/span"
    CusipTxt = "ctl00_CC_CUSIPTxt"
    CusipAAPL = "AAPL"
    CusipMSFT = "MSFT"
    CusipAMZN = "AMZN"
    SearchButton = "ctl00_CC_SearchBtn"
    SearchButton2 = "ctl00_CC_btnSearch"
    Download_button = "ctl00_CC_DownloadBtn"
    Download_button2 = "ctl00_CC_btnDownload"

    Cusip_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_CUSIPLabel"
    Symbol_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Symbol_LinkButton"
    Symbol_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_SymbolLabel"
    Activity_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Activity_LinkButton"
    Activity_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_ActivityLabel"
    Quantity_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Quantity_LinkButton"
    Quantity_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_QuantityLabel"
    EstPrice_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_EstPrice_LinkButton"
    EstPrice_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_EstPriceLabel"
    Amount_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Amount_LinkButton"
    Amount_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_AmountLabel"
    Status_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Status_LinkButton"
    Status_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_StatusLabel"
    Contra_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Contra_LinkButton"
    Contra_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_ContraLabel"
    SettleDate_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_SettleDate_LinkButton"
    SettleDate_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_SettleDateLabel"
    BussinesDate_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_BusinessDate_LinkButton"
    BussinesDate_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_BusinessDateLabel"
    Reason_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Reason_LinkButton"
    Reason_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_ReasonLabel"
    DeliverAcc_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_DelivererAcct_LinkButton"
    DeliverAcc_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_DelivererAcctLabel"
    ReceiverAcc_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_ReceiverAcct_LinkButton"
    ReceiverAcc_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_ReceiverAcctLabel"
    SubAcc_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_SubAcct_LinkButton"
    SubAcc_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_SubAcctLabel"
    Remarks_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_Remarks_LinkButton"
    Remarks_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_RemarksHyper"
    ControlNo_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_ControlNo_LinkButton"
    ControlNo_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_ControlNoLabel"
    DTCranNo_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_DTCTranNo_LinkButton"
    DTCranNo_element_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl02_DTCTranNoLabel"
    TradeStatus_header_1 = "ctl00_CC_DTCDeliveryActivityGridView_ctl01_TradeStatus_LinkButton"

    MemoSegDate_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_MemoSegDate_LinkButton"
    MemoSegDate_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_MemoSegDateLabel"
    SettleDate_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_SettleDate_LinkButton"
    SettleDate_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_SettleDateLabel"
    Cusip_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_CUSIPLabel"
    Symbol_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_Symbol_LinkButton"
    Symbol_element_2 = "//table[@id='ctl00_CC_DTCMemoSegSubmissionGridView']/tbody/tr[2]/td[6]"
    ActionQty_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_ActionQty_LinkButton"
    ActionQty_element_2 = "//table[@id='ctl00_CC_DTCMemoSegSubmissionGridView']/tbody/tr[2]/td[7]"
    Action_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_Action_LinkButton"
    Action_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_ActionLabel"
    Status_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_Status_LinkButton"
    Status_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_StatusLabel"
    ErrorDetails_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_ErrorDetails_LinkButton"
    ErrorDetails_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_ErrorDetailsLabel"
    SecNo_header_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl01_SecNo_LinkButton"
    SecNo_element_2 = "ctl00_CC_DTCMemoSegSubmissionGridView_ctl02_SecNoLabel"

    TradeDate_header_3 = "ctl00_CC_CNSFailGridView_ctl01_TradeDate_LinkButton"
    TradeDate_element_3 = "ctl00_CC_CNSFailGridView_ctl02_TradeDateLabel"
    Cusip_header_3 = "ctl00_CC_CNSFailGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_3 = "//td[3]/a"
    Symbol_header_3 = "ctl00_CC_CNSFailGridView_ctl01_Symbol_LinkButton"
    Symbol_element_3 = "ctl00_CC_CNSFailGridView_ctl02_SymbolLabel"
    SecDescription_header_3 = "ctl00_CC_CNSFailGridView_ctl01_SecurityDescription1_LinkButton"
    SecDescription_element_3 = "ctl00_CC_CNSFailGridView_ctl02_SecurityDescription1Label"
    SecType_header_3 = "ctl00_CC_CNSFailGridView_ctl01_SecurityType_LinkButton"
    SecType_element_3 = "ctl00_CC_CNSFailGridView_ctl02_SecurityTypeLabel"
    ClosingPos_header_3 = "ctl00_CC_CNSFailGridView_ctl01_ClosingNetPosition_LinkButton"
    ClosingPos_element_3 = "ctl00_CC_CNSFailGridView_ctl02_ClosingNetPositionLabel"
    Price_header_3 = "ctl00_CC_CNSFailGridView_ctl01_Price_LinkButton"
    Price_element_3 = "ctl00_CC_CNSFailGridView_ctl02_PriceLabel"
    MarketValue_header_3 = "ctl00_CC_CNSFailGridView_ctl01_MarketValue_LinkButton"
    MarketValue_element_3 = "ctl00_CC_CNSFailGridView_ctl02_MarketValueLabel"
    FailType_header_3 = "ctl00_CC_CNSFailGridView_ctl01_FailType_LinkButton"
    FailType_element_3 = "ctl00_CC_CNSFailGridView_ctl02_FailTypeLabel"
    PhysicalBox_header_3 = "ctl00_CC_CNSFailGridView_ctl01_PhysicalBox_LinkButton"

    SecNumber_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_SecurityNumber_LinkButton"
    SecNumber_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_SecurityNumberLabel"
    Cusip_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_CUSIP_LinkButton"
    Cusip_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_CUSIPLabel"
    Symbol_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_Symbol_LinkButton"
    Symbol_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_SymbolLabel"
    FailDays_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_FailDays_LinkButton"
    FailDays_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_FailDaysLabel"
    BorrowDesc_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_BorrowDesc_LinkButton"
    BorrowDesc_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_BorrowDescLabel"
    ThresholdInd_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_ThresholdInd_LinkButton"
    FailQty_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_FailQty_LinkButton"
    FailQty_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_FailQtyLabel"
    FailAmount_header_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl01_FailAmount_LinkButton"
    FailAmount_element_4 = "ctl00_CC_CNSConsecutiveFailGridView_ctl02_FailAmountLabel"

    SnapShot_header_5 = "SnapShotDate"
    SnapShot_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[2]"
    SecNum_header_5 = "SecNum"
    SecNum_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[3]"
    SecType_header_5 = "SecType"
    SecType_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[4]"
    Cusip_header_5 = "CUSIP"
    Cusip_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[5]"
    Symbol_header_5 = "Symbol"
    Symbol_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[6]"
    MarketPrice_header_5 = "MarketPrice"
    MarketPrice_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[7]"
    MarketValue_header_5 = "MarketValue"
    MarketValue_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[8]"
    Account_header_5 = "Account"
    Account_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[8]"
    Type_header_5 = "Type"
    Type_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[10]"
    Sub_header_5 = "Sub"
    Sub_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[11]"
    AccName_header_5 = "AccountName"
    AccName_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[12]"
    TradeQty_header_5 = "TradeQuantity"
    TradeQty_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[13]"
    SettleQty_header_5 = "SettleQuantity"
    SettleQty_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[14]"
    MemoQty_header_5 = "MemoQuantity"
    MemoQty_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[15]"
    MarginFree_header_5 = "MarginFree"
    MarginFree_element_5 = "//table[@id='ctl00_CC_StockRecordGridView']/tbody/tr[3]/td[16]"

    TranType_header_6 = "TranType"
    TranType_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[2]"
    Code_header_6 = "Code"
    Cusip_header_6 = "Cusip"
    Cusip_element_6 = "//td[4]/a"
    SecNum_header_6 = "SecNum"
    SecNum_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[5]"
    Symbol_header_6 = "Symbol"
    Symbol_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[6]"
    ST_header_6 = "ST"
    ST_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[7]"
    Account_header_6 = "Account"
    Account_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[8]"
    Type_header_6 = "Type"
    Type_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[9]"
    AccountName_header_6 = "AccountName"
    AccountName_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[10]"
    Quantity_header_6 = "Quantity"
    Quantity_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[11]"
    Amount_header_6 = "Amount"
    Amount_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[12]"
    Location_header_6 = "Location"
    Location_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[13]"
    Offset_header_6 = "Offset"
    Offset_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[14]"
    Eligible_header_6 = "Eligible"
    Eligible_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[15]"
    Transmit_header_6 = "Transmit"
    Control_header_6 = "Control"
    Control_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[17]"
    DTChill_header_6 = "DTCChill"
    SettleDate_header_6 = "SettleDate"
    SettleDate_element_6 = "//table[@id='ctl00_CC_FailGridView']/tbody/tr[2]/td[19]"

    PageReleaseBank_title_7 = "//td[contains(text(),'Release Bank Collateral Search Criteria')]"
    SettleDate_title_7 = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr/td"
    SettleDate_element_7 = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td"
    Version_title_7 = "ctl00_CC_SettleDateTxt"
    Version_option_7 = "//div[@id='ctl00_CC_UPP1']/table/tbody/tr/td/table/tbody/tr[2]/td[3]"

    TradeDate_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_TradeDate_LinkButton"
    TradeDate_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_TradeDateLabel"
    Account_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_Account_LinkButton"
    Account_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_AccountLabel"
    Quantity_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_Quantity_LinkButton"
    Quantity_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl03_QuantityLabel"
    SecurityID_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_SecurityID_LinkButton"
    SecurityID_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_SecurityIDLabel"
    QtyDebit_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_QtyDebitCredit_LinkButton"
    QtyDebit_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_QtyDebitCreditLabel"
    Amount_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_Amount_LinkButton"
    Amount_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_AmountLabel"
    Status_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_BLSStatus_LinkButton"
    Status_element_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl02_BLSStatusLabel"
    ErrorMsg_header_8 = "ctl00_CC_BankLoanBookkeepingGridView_ctl01_ErrorMessage_LinkButton"

    Description_9 = "Description"
    Date1_header_9 = "//th[2]/a"
    Date2_header_9 = "//th[3]/a"
    Date3_header_9 = "//th[4]/a"
    Date1_element_9 = "//table[@id='ctl00_CC_ClearingFundSummaryGrid']/tbody/tr[2]/td[2]"
    Date2_element_9 = "//table[@id='ctl00_CC_ClearingFundSummaryGrid']/tbody/tr[2]/td[3]"
    Date3_element_9 = "//table[@id='ctl00_CC_ClearingFundSummaryGrid']/tbody/tr[2]/td[4]"
    Allocation_header_9 = "//table[@id='ctl00_CC_AllocationGridview']/tbody/tr/th"
    Date4_header_9 = "//table[@id='ctl00_CC_AllocationGridview']/tbody/tr/th[2]"
    Date5_header_9 = "//table[@id='ctl00_CC_AllocationGridview']/tbody/tr/th[3]"
    Date6_header_9 = "//table[@id='ctl00_CC_AllocationGridview']/tbody/tr/th[4]"
    Date4_element_9 = "//div[2]/table/tbody/tr[2]/td[2]/a"
    Date5_element_9 = "//div[2]/table/tbody/tr[2]/td[3]/a"
    Date6_element_9 = "//div[2]/table/tbody/tr[2]/td[4]/a"

    Sub_header_10 = "Sub"
    Sub_element_10 = "//tr[2]/td/a"
    FirmName_header_10 = "FirmName"
    FirmName_element_10 = "//td[2]/a"
    DaysInRange_header_10 = "DaysInRange"
    DaysInRange_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[3]"
    DaysInCharge_header_10 = "DaysInCharge"
    DaysInCharge_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[4]"
    AverageChargeOver_header_10 = "AverageChargeOverRange"
    AverageChargeOver_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[5]"
    AverageCharge_header_10 = "AverageCharge"
    AverageCharge_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[6]"
    MaxCharge_header_10 = "MaxCharge"
    MaxCharge_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[7]"
    MinCharge_header_10 = "MinCharge"
    MinCharge_element_10 = "//table[@id='ctl00_CC_ClearingFundSummaryByFirmGrid']/tbody/tr[2]/td[8]"

    Source_header_11 = "Source"
    Source_element_11 = "//tr[2]/td/div/a"
    Age_header_11 = "Age"
    Age_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[2]/div"
    SecurityNumber_header_11 = "Security#"
    SecurityNumber_element_11 = "//td[3]/div/a"
    Cusip_header_11 = "CUSIP"
    Cusip_element_11 = "//td[4]/div/a"
    Symbol_header_11 = "Symbol"
    Symbol_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[5]/div"
    SecurityDest_header_11 = "SecurityDescription"
    SecurityDest_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[6]/div"
    Deficit_header_11 = "DEFICIT"
    Deficit_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[7]/div"
    Note_header_11 = "Note"
    UserName_header_11 = "UserName"
    UserName_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[9]/div"
    NoteDate_header_11 = "NoteDate"
    FR_header_11 = "F_R"
    Short1_header_11 = "SHORT1"
    Type6_header_11 = "TYPE6"
    Short2_header_11 = "SHORT2"
    SL_header_11 = "S_L"
    SB_header_11 = "S_B"
    Seg_header_11 = "SEG"
    Under_header_11 = "UNDER"
    Price_header_11 = "Price"
    Price_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[20]/div"
    Under_element_11 = "//table[@id='ctl00_CC_defTracking']/tbody/tr[2]/td[18]/div"
    Text_header_11 = "ctl00_CC_lblPageApproval"

    TradeDate_header_12 = "TradeDate"
    TradeDate_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[2]"
    Source_header_12 = "Source"
    Source_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[3]"
    Symbol_header_12 = "Symbol"
    Symbol_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[4]"
    Cusip_header_12 = "Cusip_sec"
    Cusip_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[5]"
    CallPut_header_12 = "CallPut"
    CallPut_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[6]"
    StrikerPrice_header_12 = "StrikePrice"
    StrikerPrice_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[7]"
    ExpirationDate_header_12 = "ExpirationDate"
    ExpirationDate_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[8]"
    OccLong_header_12 = "OccLong"
    OccLong_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[9]"
    OccShort_header_12 = "OccShort"
    OccShort_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[10]"
    ContraLog_header_12 = "ContraLong"
    ContraLog_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[11]"
    ContraShort_header_12 = "ContraShort"
    ContraShort_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[12]"
    CustomerLong_header_12 = "CustomerLong"
    CustomerLong_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[13]"
    CustomerShort_header_12 = "CustomerShort"
    CustomerShort_element_12 = "//table[@id='ctl00_CC_OccGridView']/tbody/tr[2]/td[14]"
    Compare_header_12 = "CompareResult"
    UserName_header_12 = "UserName"
    LastInsert_header_12 = "LastInsertUpdateTime"

    AccNumber_header_13 = "Acct Number"
    AccNumber_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[4]"
    AccName_header_13 = "Account Name"
    AccName_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[5]"
    Department_header_13 = "Department"
    Department_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[6]"
    Name_header_13 = "Name"
    Name_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[7]"
    Source_header_13 = "Source"
    Source_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[8]"
    AccountType_header_13 = "AccountType"
    AccountType_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[9]"
    BankAcc_header_13 = "Bank Acct Indicator"
    BankAcc_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[10]"
    a15c3_header_13 = "15c3"
    EffectiveDate_header_13 = "Effective Date"
    EffectiveDate_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[12]"
    EndDate_header_13 = "End Date"
    IsActive_header_13 = "IsActive"
    IsActive_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[14]"
    CreatedDate_header_13 = "Created Date"
    CreatedDate_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[15]"
    CreatedBy_header_13 = "Created By"
    CreatedBy_element_13 = "//table[@id='ctl00_WG_OperationsAccountBalanceGridView']/tbody/tr[3]/td[16]"
    UpdatedDate_header_13 = "Updated Date"
    UpdatedBy_header_13 = "Updated By"
    Edit_button_13 = "ctl00_WG_OperationsAccountBalanceGridView_ctl03_EditBtn"
    Deactivate_button_13 = "ctl00_WG_OperationsAccountBalanceGridView_ctl03_DeleteBtn"

    TradeDate_header_14 = "TradeDate"
    TradeDate_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[2]"
    AccountNumber_header_14 = "Account Number"
    AccountNumber_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[3]"
    Cusip_header_14 = "CUSIP"
    Cusip_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[4]"
    SecurityName_header_14 = "Security Name"
    SecurityName_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[5]"
    Quantity_header_14 = "Quantity"
    Quantity_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[6]"
    NetTrade_header_14 = "NetTradeAmt"
    NetTrade_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[7]"
    TransCode_header_14 = "TransCode"
    TransCode_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[8]"
    RefNum_header_14 = "RefNum"
    RefNum_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[9]"
    SettleDate_header_14 = "SettleDate"
    SettleDate_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[10]"
    ProcDate_header_14 = "ProcDate"
    ProcDate_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[11]"
    Currency_header_14 = "Currency"
    Currency_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[12]"
    Descr_header_14 = "Descr"
    Descr_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[13]"
    RRCode_header_14 = "RRCode"
    RRCode_element_14 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[14]"

    SnapDate_header_15 = "SnapshotDate"
    SnapDate_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[2]"
    Account_header_15 = "Account"
    Account_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[3]"
    EventID_header_15 = "EventID"
    EventID_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[4]"
    EventType_header_15 = "EventType"
    EventType_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[5]"
    Security_header_15 = "Security"
    Security_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[6]"
    SecurityName_header_15 = "SecurityName"
    ExDate_header_15 = "ExDate"
    ExDate_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[8]"
    RecordDate_header_15 = "RecordDate"
    RecordDate_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[9]"
    PayableDate_header_15 = "PayableDate"
    PayableDate_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[10]"
    Status_header_15 = "Status"
    Status_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[11]"
    DebitCredit1_header_15 = "DebitCreditInd1"
    DebitCredit1_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[12]"
    Security1_header_15 = "Security1"
    Security1_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[13]"
    Rate1_header_15 = "Rate1"
    Rate1_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[14]"
    CurrentQty_header_15 = "CurrentQuantity"
    CurrentQty_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[15]"
    DebitCredit2_header_15 = "DebitCreditInd2"
    DebitCredit2_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[16]"
    Security2_header_15 = "Security2"
    Security2_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[17]"
    Rate2_header_15 = "Rate2"
    Rate2_element_15 = "//table[@id='ctl00_WG_CanaccordTradeReportGridView']/tbody/tr[2]/td[18]"

    OrderType_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_OrderType_LinkButton"
    OrderType_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_OrderTypeLabel"
    Units_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Units_LinkButton"
    Units_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_UnitsLabel"
    BrokerCode_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_BrokerCode_LinkButton"
    BrokerCode_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_BrokerCodeLabel"
    TradeDate_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_TradeDate_LinkButton"
    TradeDate_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_TradeDateLabel"
    SettlementDate_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SettlementDate_LinkButton"
    SettlementDate_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SettlementDateLabel"
    Country_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Country_LinkButton"
    OrderNumber_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_OrderNumber_LinkButton"
    OrderNumber_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_OrderNumberLabel"
    ISIN_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_ISIN_LinkButton"
    ISIN_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_ISINLabel"
    Sedol_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Sedol_LinkButton"
    Sedol_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SedolLabel"
    Cusip_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Cusip_LinkButton"
    Cusip_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_CusipLabel"
    Symbol_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Symbol_LinkButton"
    Symbol_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SymbolLabel"
    SecurityName_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SecurityName_LinkButton"
    SecurityName_element_16 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[2]/td[13]"
    Price_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Price_LinkButton"
    Price_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_PriceLabel"
    SetLoc_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SettlementLoc_LinkButton"
    SetLoc_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SettlementLocLabel"
    BasketShares_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_BasketShares_LinkButton"
    BasketShares_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_BasketSharesLabel"
    SharesDel_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SharesDelRec_LinkButton"
    SharesDel_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SharesDelRecLabel"
    SharesRemain_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SharesRemaining_LinkButton"
    SharesRemain_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SharesRemainingLabel"
    CollateralValue_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_CollateralValue_LinkButton"
    CollateralValue_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_CollateralValueLabel"
    SetStatus_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_SettlementStatus_LinkButton"
    SetStatus_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl03_SettlementStatusLabel"
    Editby_header_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_EditedBy_LinkButton"
    Country_element_16 = "ctl00_WG_ETFOrderDetailReportGridView_ctl02_Country_LinkButton"

    ETFPage_title_18 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr/td"
    TradeDate_title_18 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td"
    TradeDate_field_18 = "ctl00_CC_tbTradeDate"
    SettleDate_title_18 ="//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[3]"
    SettleDate_field_18 = "ctl00_CC_tbSettleDate"
    OrderNumber_title_18 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[5]"
    OrderNumber_field_18 = "ctl00_CC_tbOrderNumber"
    BrokerCode_title_18 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[2]/td[7]"
    BrokerCode_field_18 = "ctl00_CC_tbBrokerCode"

    FundID_header_19 = "FundId"
    FundID_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[2]"
    OrderNumber_header_19 = "OrderNumber"
    OrderNumber_element_19 = "//td[3]/a"
    Type_header_19 = "Type"
    Type_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[4]"
    TradeDate_header_19 = "TradeDate"
    TradeDate_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[5]"
    SettleDate_header_19 = "SettleDate"
    SettleDate_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[6]"
    Units_header_19 = "Units"
    Units_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[7]"
    BrokerCode_header_19 = "BrokerCode"
    BrokerCode_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[8]"
    BrokerName_header_19 = "BrokerName"
    BrokerName_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[9]"
    FundName_header_19 = "FundName"
    FundName_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[10]"
    ETFShares_header_19 = "ETFShares"
    ETFShares_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[11]"
    MarketMarker_header_19 = "MarketMaker"
    MarketMarker_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[12]"
    Cash_header_19 = "CashActual"
    Cash_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[13]"
    SettlementStatus_header_19 = "SettlementStatus"
    SettlementStatus_element_19 = "//table[@id='ctl00_WG_ETFOrderReportGridView']/tbody/tr[2]/td[14]"

    SnapshotDate_header_20 = "SnapshotDate"
    SnapshotDate_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[2]"
    OrderNumber_header_20 = "OrderNumber"
    OrderNumber_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[3]"
    OrderType_header_20 = "OrderType"
    OrderType_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[4]"
    Units_header_20 = "Units"
    Units_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[5]"
    BrokerCode_header_20 = "BrokerCode"
    BrokerCode_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[6]"
    TradeDate_header_20 = "TradeDate"
    TradeDate_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[7]"
    SettleDate_header_20 = "SettleDate"
    SettleDate_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[8]"
    ISIN_header_20 = "ISIN"
    ISIN_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[9]"
    BasketShares_header_20 = "BasketShares"
    BasketShares_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[10]"
    Cusip_header_20 = "Cusip"
    Cusip_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[11]"
    Sedol_header_20 = "Sedol"
    Sedol_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[12]"
    SecurityName_header_20 = "SecurityName"
    SecurityName_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[13]"
    SettlementLocation_header_20 = "SettlementLocation"
    SettlementLocation_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[14]"
    SharesDel_header_20 = "SharesDeliveredReceived"
    SharesDel_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[15]"
    Inkind_header_20 = "InKindOrCash"
    Inkind_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[16]"
    SharesRemain_header_20 = "SharesRemaining"
    SharesRemain_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[17]"
    Price_header_20 = "Price"
    Price_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[18]"
    SharesRemainMkt_header_20 = "SharesRemainingMarketValue"
    SharesRemainMkt_element_20 = "//table[@id='ctl00_WG_ETFOrderDetailReportGridView']/tbody/tr[3]/td[19]"

    CreateRedeem_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[2]"
    FundSymbol_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[3]"
    Units_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[4]"
    CashInk_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[5]"
    Clearing_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[6]"
    CashAmount_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[7]"
    TransactionFee_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[8]"
    SettleDate_element_21 = "//div[@id='ctl00_CC_HeaderPanel']/table/tbody/tr[3]/td[9]"
    CreateReddem_header_21 = "ctl00_CC_ddlCreateRedeem1"
    FundSymbol_header_21 = "ctl00_CC_txtFundSymbol1"
    Units_header_21 = "ctl00_CC_txtQty1"
    CashInk_header_21 = "ctl00_CC_ddlCashInKind1"
    Clearing_header_21 = "ctl00_CC_chkExClearing1"
    CashAmount_header_21 = "ctl00_CC_txtCashAmount1"
    TransactionFee_header_21 = "ctl00_CC_txtTransactionFee1"
    SettleDate_header_21 = "ctl00_CC_txtSettleDate1"
    Text1_line_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[2]/td"
    Text2_line_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[3]/td"
    Text3_line_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[4]/td"
    ViewChange_title_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[8]/td"
    TradeDate_title_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[9]/td[2]"
    TradeDate_field_21 = "ctl00_CC_txtViewTradeDate"
    AccountNumber_title_21 = "//div[@id='ctl00_CC_HeaderPanel']/table[2]/tbody/tr[9]/td[4]"
    AccountNumber_field_21 = "ctl00_CC_ddlViewAccounts"

    Recap_title = "ctl00_CC_Label1"
    Recap_title_text = "Recap Report Generator"
    Generate_button = "ctl00_CC_Button1"
    Generate_button_text = "Generate Recap Report"

    ReportDate_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_ReportDate_LinkButton"
    ReportDate_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_ReportDateLabel"
    Cusip_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_CUSIP_LinkButton"
    Cusip_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_CUSIPLabel"
    SecNum_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_SecNum_LinkButton"
    SecNum_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_SecNumLabel"
    Symbol_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_Symbol_LinkButton"
    Symbol_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_SymbolLabel"
    Rate_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_Rate_LinkButton"
    Rate_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_RateLabel"
    UnallocatedQty_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_UnallocatedQty_LinkButton"
    UnallocatedQty_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_UnallocatedQtyLabel"
    UnallocatedCost_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_UnallocatedCost_LinkButton"
    UnallocatedCost_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_UnallocatedCostLabel"
    Days_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_Days_LinkButton"
    Days_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_DaysLabel"
    TotalCost_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_TotalCost_LinkButton"
    TotalCost_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_TotalCostLabel"
    BorrowQty8199_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_BorrowQty8199_LinkButton"
    BorrowQty8199_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_BorrowQty8199Label"
    BorrowQty0103_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_BorrowQty0103_LinkButton"
    BorrowQty0103_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_BorrowQty0103Label"
    CNSFail8199_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_CNSFail8199_LinkButton"
    CNSFail8199_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_CNSFail8199_Label"
    CNSFail0103_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_CNSFail0103_LinkButton"
    CNSFail0103_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_CNSFail0103_Label"
    BrokerFail8199_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_BrokerFail8199_LinkButton"
    BrokerFail8199_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_BrokerFail8199_Label"
    BrokerFail0103_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_BrokerFail0103_LinkButton"
    BrokerFail0103_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_BrokerFail0103_Label"
    IDP3_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_IDP3_LinkButton"
    IDBeta_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_IDBeta_LinkButton"
    Notes_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_Notes_LinkButton"
    UpdatedBy_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_UpdatedBy_LinkButton"
    UpdatedBy_element_22 ="ctl00_WG_UnallocatedBorrowCostGridView_ctl03_UpdatedBy_Label"
    Updated_header_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl02_Updated_LinkButton"
    Updated_element_22 = "ctl00_WG_UnallocatedBorrowCostGridView_ctl03_Updated_Label"

    ReportType_23 = "ctl00_CC_ReportTypeDpl"
    TestReportType_23 = "BETA"
    System_header_23 = "System"
    System_element_23 = "//table[@id='ctl00_CC_LargeCustomerBuysDetailGrid']/tbody/tr[2]/td"
    SettleDate_header_23 = "Settle Date"
    SettleDate_element_23 = "//table[@id='ctl00_CC_LargeCustomerBuysDetailGrid']/tbody/tr[2]/td[2]"
    TotalNet_header_23 = "Total Net Amount"
    TotalNet_element_23 = "//table[@id='ctl00_CC_LargeCustomerBuysDetailGrid']/tbody/tr[2]/td[3]"
    DetailReport_header_23 = "//table[@id='ctl00_CC_LargeCustomerBuysDetailGrid']/tbody/tr/td"
    DetailReport_element_23 = "BETA Detail Report for 12/31/2020"

    runDate = "ctl00_CC_runDate"
    changeDate = "ctl00_CC_LinkButton1"




