
class TreasuryPage(object):
    Treasury_header = "Treasury"
    FDICSweep_header = "FDIC Sweep Monitoring"

    SettleDate = "ctl00_CC_SettleDateTxt"
    SearchButton = "ctl00_CC_SearchBtn"
    NADashboard_Charts = "/html[1]/body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[1]"

    AccountNumber_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td"
    AccountNam1_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[2]"
    AccountName2_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[3]"
    RepCode_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[4]"
    MMFProduct_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[5]"
    FDICSweep_element_1 = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[6]"
    Instituional_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[7]"
    CSICode_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[8]"
    MSICode_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[9]"
    PDT_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[10]"
    IndexedForm_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[11]"
    IndexedDate_element = "//table[@id='ctl00_WG_GridView1']/tbody/tr[2]/td[12]"
    AccountNumber_header = "AccountNumber"
    AccountNam1_header = "AccountName1"
    AccountName2_header = "AccountName2"
    RepCode_header = "RepCode"
    MMFProduct_header = "MMF_Product"
    FDICSweep_header_1 = "FDIC Sweep Balance"
    Instituional_header = "Instituional_Code"
    CSICode_header = "CSI_Code"
    MSICode_header = "MSI_Code"
    PDT_header_header = "PDT"
    IndexedForm_header = "Indexed Form"
    IndexedDate_header = "Indexed Date"
