
class WealthManagementPage(object):
    WealthManagement_header = "Wealth Management"
    PCSProfig_header = "PCS Profit Loss Report"
    MFCash_header = "MF Cash Flow"

    SettleDate = "ctl00_CC_SettleDateTxt"
    SearchButton = "ctl00_CC_SearchBtn"
    NADashboard_Charts = "/html[1]/body[1]/form[1]/center[1]/table[1]/tbody[1]/tr[1]"

    TradeDate_header = "TradeDate"
    TradeDate_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[2]"
    Firm_header = "FIRM"
    Firm_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[3]"
    PurchasesMTD_header = "Purchases_MTD"
    PurchasesMTD_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[4]"
    Purchases_FY_header = "Purchases_FY_YTD"
    Purchases_FY_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[5]"
    PurchasesPrev_header = "Purchases_Prev_FY"
    PurchasesPrev_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[6]"
    SellsMTD_header = "Sells_MTD"
    SellsMTD_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[7]"
    SellsFY_header = "Sells_FY_YTD"
    SellsFY_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[8]"
    SellsPrev_header = "Sells_Prev_FY"
    SellsPrev_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[9]"
    NetFlowsMTD_header = "NetFlows_MTD"
    NetFlowsMTD_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[10]"
    NetFlowsFY_header = "NetFlows_FY_YTD"
    NetFlowsFY_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[11]"
    NetFlowsPrev_header = "NetFlows_Prev_FY"
    NetFlowsPrev_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[12]"
    YoyFlow_header = "Y-O-Y_Flow"
    YoyFlow_element = "//table[@id='ctl00_CC_MFCashFlowGridView']/tbody/tr[2]/td[13]"
