
vusername = "islaso"
vpassword = "rIder08gibbs"
browser = "chrome"
pathchrome = 'C:\Wdrivers\chromedriver.exe'
pathfirefox = 'C:\Wdrivers\geckodriver.exe'
pathedge = 'C:\Wdrivers\msedgedriver.exe'
pathie = 'C:\Wdrivers\IEDriverServer.exe'


projectZephyr = "QTML"
#token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ZjhjNzFlMi1hYjMwLTNkZmEtOTQ3MS1iNjJkMmIzZDFkZDQiLCJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczpcL1wvd2VkYnVzaC5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI1ZDlmNjAxZmM2MmY4NDBkYjJiNmYzNDkifX0sImlzcyI6ImNvbS5rYW5vYWgudGVzdC1tYW5hZ2VyIiwiZXhwIjoxNjQ2MzM0MDk1LCJpYXQiOjE2MTQ3OTgwOTV9.r0aS_J_CjefPiOxptyz_4_DUFlwkZlesDKunH9yeFxk"
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ZjhjNzFlMi1hYjMwLTNkZmEtOTQ3MS1iNjJkMmIzZDFkZDQiLCJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczpcL1wvd2VkYnVzaC5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI1ZDlmNjAxZmM2MmY4NDBkYjJiNmYzNDkifX0sImlzcyI6ImNvbS5rYW5vYWgudGVzdC1tYW5hZ2VyIiwiZXhwIjoxNjY1NTk3Mjg1LCJpYXQiOjE2MzQwNjEyODV9.PzMwhSzLJ69b4UD5EH4z5kLtTCm1sFQB0aGOZORAHBw"

